kind = "web"
previewPath = "/"
title = "z0h1x - Links"
version = "1.0.0"
id = "artifacts/z0h1x"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20523

[services.development]
run = "pnpm --filter @workspace/z0h1x run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/z0h1x", "run", "build" ]
publicDir = "artifacts/z0h1x/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20523"
BASE_PATH = "/"
